"""Finite harmonic l-sum evaluator with optional CUDA matrix acceleration."""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

from .kuntz_benchmark import KUNTZ_SEED_EPSILONS
from .spectral_convergence import (
    PHYSICAL_PTA_TRANSFER_SCALE,
    _external_coefficients,
    _source_grid,
    _source_harmonic_matrix,
    _unit,
    _validate_epsilons,
    _validate_observables,
)


@dataclass(frozen=True)
class SpectralSumResult:
    """One finite l-sum four-point evaluation."""

    observables: tuple[str, str, str, str]
    lmax: int
    value: complex
    n_theta: int
    n_phi: int
    backend: str


def _array_module(backend: str):
    key = backend.lower()
    if key in {"cpu", "numpy"}:
        return np, "numpy"
    if key in {"cuda", "gpu", "cupy"}:
        import cupy as cp

        return cp, "cupy"
    if key == "auto":
        try:
            import cupy as cp

            if cp.cuda.runtime.getDeviceCount() > 0:
                return cp, "cupy"
        except Exception:
            pass
        return np, "numpy"
    raise ValueError("backend must be 'numpy', 'cupy', 'cuda', 'gpu', or 'auto'")


def _to_complex(value, xp) -> complex:
    if xp is np:
        return complex(value)
    return complex(value.get())


class SpectralSumEvaluator:
    """Evaluate finite physical harmonic sums for P/A four-point kernels.

    Special-function values are generated by the package's spin-harmonic code
    and cached. The optional CUDA backend accelerates the matrix contractions
    and source-grid integration once those matrices are available.
    """

    def __init__(
        self,
        *,
        lmax: int,
        n_theta: int | None = None,
        n_phi: int | None = None,
        backend: str = "auto",
        transfer_scale: float = PHYSICAL_PTA_TRANSFER_SCALE,
    ):
        if lmax < 2:
            raise ValueError("lmax must be at least 2")
        self.lmax = int(lmax)
        self.n_theta = 2 * lmax + 8 if n_theta is None else int(n_theta)
        self.n_phi = 4 * lmax + 16 if n_phi is None else int(n_phi)
        self.transfer_scale = float(transfer_scale)
        self.xp, self.backend = _array_module(backend)
        _theta_grid, _phi_grid, weights = _source_grid(self.n_theta, self.n_phi)
        self.weights = self.xp.asarray(weights)
        self._source_cache: dict[int, tuple[tuple[tuple[int, int], ...], object]] = {}

    def _source_values(self, source_spin: int):
        if source_spin not in self._source_cache:
            modes, values = _source_harmonic_matrix(
                self.lmax,
                source_spin,
                self.n_theta,
                self.n_phi,
            )
            self._source_cache[source_spin] = (modes, self.xp.asarray(values))
        return self._source_cache[source_spin]

    def response_on_source_grid(self, observable: str, vector, epsilon: int):
        """Return the finite l-summed response on the source grid."""

        source_spin = 2 * epsilon
        modes, source_values = self._source_values(source_spin)
        coefficients = _external_coefficients(
            _unit(vector),
            observable,
            epsilon,
            modes,
            transfer_scale=self.transfer_scale,
        )
        return self.xp.asarray(coefficients) @ source_values

    def evaluate(
        self,
        observables,
        vectors,
        epsilons: tuple[int, int, int, int] = KUNTZ_SEED_EPSILONS,
    ) -> SpectralSumResult:
        """Evaluate one finite l-sum four-point kernel."""

        observables = _validate_observables(observables)
        epsilons = _validate_epsilons(epsilons)
        unit_vectors = tuple(_unit(vector) for vector in vectors)
        if len(unit_vectors) != 4:
            raise ValueError("four directions are required")
        product = self.xp.ones(self.weights.shape, dtype=complex)
        for observable, vector, epsilon in zip(observables, unit_vectors, epsilons):
            product *= self.response_on_source_grid(observable, vector, epsilon)
        value = self.xp.sum(self.weights * product) / (4.0 * math.pi)
        return SpectralSumResult(
            observables=observables,
            lmax=self.lmax,
            value=_to_complex(value, self.xp),
            n_theta=self.n_theta,
            n_phi=self.n_phi,
            backend=self.backend,
        )

    def evaluate_family(
        self,
        vectors,
        epsilons: tuple[int, int, int, int] = KUNTZ_SEED_EPSILONS,
    ) -> dict[tuple[str, str, str, str], complex]:
        """Evaluate the PPPP-to-AAAA finite l-sum family."""

        cases = (
            ("P", "P", "P", "P"),
            ("A", "P", "P", "P"),
            ("A", "A", "P", "P"),
            ("A", "A", "A", "P"),
            ("A", "A", "A", "A"),
        )
        return {case: self.evaluate(case, vectors, epsilons).value for case in cases}


def spectral_sum_average(
    observables,
    vectors,
    epsilons: tuple[int, int, int, int] = KUNTZ_SEED_EPSILONS,
    *,
    lmax: int,
    n_theta: int | None = None,
    n_phi: int | None = None,
    backend: str = "auto",
) -> complex:
    """Convenience wrapper for one finite l-sum evaluation."""

    evaluator = SpectralSumEvaluator(
        lmax=lmax,
        n_theta=n_theta,
        n_phi=n_phi,
        backend=backend,
    )
    return evaluator.evaluate(observables, vectors, epsilons).value
